# Generated by assistant: add client_id field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_remove_image_url_image_image_alter_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='client_id',
            field=models.CharField(blank=True, max_length=100, null=True, help_text='Client identifier for the image'),
        ),
    ]
