# Generated by assistant: make client_id required
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_add_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='client_id',
            field=models.CharField(default='', max_length=100, null=False, blank=False, help_text='Client identifier for the image'),
            preserve_default=False,
        ),
    ]
