# Generated by Django 5.0.14 on 2026-01-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_make_client_id_required'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['client_id'], name='idx_image_client_id'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['-uploaded_at'], name='idx_image_uploaded_desc'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['uploaded_at'], name='idx_image_uploaded_asc'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['size'], name='idx_image_size'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['-size'], name='idx_image_size_desc'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['client_id', '-uploaded_at'], name='idx_image_client_date'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['filename'], name='idx_image_filename'),
        ),
    ]
