# Generated by Django 5.0.14 on 2026-01-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='download_count',
            field=models.IntegerField(default=0, help_text='Number of times the image has been downloaded'),
        ),
    ]
