# Generated by Django 5.0.14 on 2026-01-05 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_image_download_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='download_count',
        ),
        # Remove is_deleted column if it exists (from old code)
        migrations.RunSQL(
            sql='ALTER TABLE assets_image DROP COLUMN IF EXISTS is_deleted;',
            reverse_sql='ALTER TABLE assets_image ADD COLUMN is_deleted BOOLEAN DEFAULT FALSE;',
        ),
    ]
