# Generated by Django 5.0.14 on 2026-01-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_remove_image_download_count'),
    ]

    operations = [
        # Remove all old unused columns from previous code
        migrations.RunSQL(
            sql='''
                ALTER TABLE assets_image DROP COLUMN IF EXISTS deleted_at;
                ALTER TABLE assets_image DROP COLUMN IF EXISTS deleted_by;
                ALTER TABLE assets_image DROP COLUMN IF EXISTS file_type;
                ALTER TABLE assets_image DROP COLUMN IF EXISTS is_starred;
                ALTER TABLE assets_image DROP COLUMN IF EXISTS tags;
                ALTER TABLE assets_image DROP COLUMN IF EXISTS updated_at;
            ''',
            reverse_sql='''
                ALTER TABLE assets_image ADD COLUMN deleted_at TIMESTAMP;
                ALTER TABLE assets_image ADD COLUMN deleted_by VARCHAR(255);
                ALTER TABLE assets_image ADD COLUMN file_type VARCHAR(50);
                ALTER TABLE assets_image ADD COLUMN is_starred BOOLEAN;
                ALTER TABLE assets_image ADD COLUMN tags TEXT;
                ALTER TABLE assets_image ADD COLUMN updated_at TIMESTAMP;
            ''',
        ),
    ]
