# Generated by Django 5.0.14 on 2026-01-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20260105_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingFileDeletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Path to file in storage', max_length=500)),
                ('client_id', models.CharField(blank=True, help_text='Client ID for logging', max_length=100, null=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True, help_text='When the file was queued for deletion')),
                ('attempts', models.IntegerField(default=0, help_text='Number of deletion attempts')),
                ('last_error', models.TextField(blank=True, help_text='Last deletion error if any', null=True)),
            ],
            options={
                'verbose_name': 'Pending File Deletion',
                'verbose_name_plural': 'Pending File Deletions',
                'ordering': ['queued_at'],
                'indexes': [models.Index(fields=['queued_at'], name='idx_pending_del_queued'), models.Index(fields=['attempts'], name='idx_pending_del_attempts')],
            },
        ),
    ]
