# Generated by Django 6.0 on 2025-12-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Unique filename stored in R2', max_length=255, unique=True)),
                ('url', models.URLField(help_text='Full public URL of the image', max_length=500)),
                ('original_filename', models.CharField(help_text='Original uploaded filename', max_length=255)),
                ('name', models.CharField(blank=True, help_text='Custom name for the image', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the image', null=True)),
                ('size', models.IntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Upload timestamp')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
